### PR TITLE
add docker and proper docker-compose support

### PR DESCRIPTION
**Pull request by w9n**
Just seeing your blog post, nice work! Not sure if you even want this in one of the repos.
email is not working yet in compose.

### CODE REVIEW

**Comment by bradymholt** [comment]
I usually don't use Docker for the main app (.NET Core) since it seems like overkill but I'm open to trying to understand the pros in doing so.  Does this make it easier to deploy or is the Dockerization more of a dogmatic approach of keeping the entire app in Docker?

**Comment by w9n** [comment]
The main reason is for deployment. You can basically setup a secure remote docker api on your server like [here](https://docs.docker.com/engine/security/https/) and then directly deploy, update, backup, delete the individual container via the dockerhost parameter in the docker cli. This is more or less mandatory in some form for cluster, HA and scalability and keeps all dependencys but docker away from the host.

You could also extend the postgres image with your backup script and use this one image without build dependencys as source of all your various projects, or remove all deployment depencenys but a dockerfile from your web app porjects and deploy them through one docker-compose project with one [web Dockerfile](https://github.com/bradyholt/aspnet-core-react-template/pull/10/files#diff-4e5e90c6228fd48698d074241c2ba760R10) parameter. 

[Ansible-Container](https://docs.ansible.com/ansible-container/getting_started.html) looks very nice but it seems unmature to manage service-discovery variations in docker and cluster environments.

**Comment by w9n** [comment]
there is still a major issue with frontEndUrl (need rename, its JwtBearer authority) in local compose deployment. the host parameter of a login request must be the same as the authority setting in UseJwtBearerAuthentication(). When starting locally the browser resolves 127.0.0.1.nip.io to 127.0.0.1:80 where nginx listens, which then forwards the requests to the webapp on port 5000 with its initial 127.0.0.1.nip.io Host header. But when the webapp tries to access 127.0.0.1.nip.io in its container it doesnt route through nginx but stays on its loopback where nothing is listening to port 80.

**Comment by bradymholt** [comment]
Closing this out - feel free to fork!

**Pull request closed without merging**
